#!/bin/sh
NAME=dnsd
DAEMON=/usr/sbin/$NAME
DESC="Busybox DNS Server"
CONF="/etc/dnsd.conf"
ARGS="-c $CONF"
PIDFILE=/var/run/$NAME.pid

test -f $DAEMON || exit 1

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "
	if [ ! -f $CONF ]; then
		echo "error: $CONF is missing."
		exit 1
	fi
	/sbin/start-stop-daemon -S -b -m -p $PIDFILE -a $DAEMON -- $ARGS
	echo "done."
	;;
    stop)
        echo -n "stopping $DESC: $NAME... "
	/sbin/start-stop-daemon -K -p $PIDFILE
	echo "done."
	;;
    restart)
        echo "restarting $DESC: $NAME... "
 	$0 stop
	$0 start
	echo "done."
	;;
    reload)
    	echo -n "reloading $DESC: $NAME... "
    	killall -HUP $(basename ${DAEMON})
	echo "done."
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
