#!/bin/sh
MDEV=/sbin/mdev
DESC="Busybox mdev setup"

splash_progress PLACEHOLDER

# Complain if thing's aren't right
if [ ! -e /proc/filesystems ]; then
  echo "mdev requires a mounted procfs, not started."
  exit 1
fi

if ! grep -q '[[:space:]]tmpfs$' /proc/filesystems; then
  echo "mdev requires tmpfs support, not started."
  exit 1
fi

if [ ! -d /sys/class/ ]; then
  echo "mdev requires a mounted sysfs, not started."
  exit 1
fi

if [ ! -e /proc/sys/kernel/hotplug ]; then
  echo "mdev requires hotplug support, not started."
  exit 1
fi

#mdev_dash_s SECTION_START
# Create tmpfs for /dev
if mount | grep -q 'devtmpfs on /dev type devtmpfs'; then
  echo "Using existing devtmpfs for /dev"
else
  # We need to unmount /dev/pts/ and remount it later over the tmpfs
  if mountpoint -q /dev/pts/; then
    umount -l /dev/pts/
  fi

  if mountpoint -q /dev/shm/; then
    umount -l /dev/shm/
  fi

  echo "Creating tmpfs at /dev"
  mount -t tmpfs tmpfs /dev -o size=64k,mode=0755
fi;
#mdev_dash_s SECTION_END

# Register mdev as hotplug event helper
echo "$MDEV" > /proc/sys/kernel/hotplug

#mdev_dash_s SECTION_START
# Populate /dev from /sys info
echo "Populating /dev using mdev"
$MDEV -s
#mdev_dash_s SECTION_END

# Touch .udev to inform scripts that /dev needs no further setup
touch /dev/.udev

if ! mountpoint -q /dev/pts/ ; then
  # Mount devpts
  TTYGRP=5
  TTYMODE=620
  mkdir -m 755 -p /dev/pts
  if [ ! -e /dev/ptmx ]; then
      mknod -m 666 /dev/ptmx c 5 2
  fi
  mount -t devpts devpts /dev/pts -onoexec,nosuid,gid=$TTYGRP,mode=$TTYMODE
fi

if ! mountpoint -q /dev/shm/ ; then
  # Make shm directory
  mkdir -m 755 -p /dev/shm
  mount -t tmpfs tmpfs /dev/shm -omode=0777
fi

# Make extraneous links
ln -sf /proc/self/fd /dev/
ln -sf /proc/self/fd/0 /dev/stdin
ln -sf /proc/self/fd/1 /dev/stdout
ln -sf /proc/self/fd/2 /dev/stderr
ln -sf /proc/kcore /dev/core
ln -sf /proc/asound/oss/sndstat /dev/sndstat

exit 0
