#! /bin/sh

PIDFILE=/var/run/syslogd.pid
FILE="-O /var/log/messages"
#REMOTE="-L -R host[:port]"
#ROTATE_SIZE="-s SIZE"
#ROTATE_N="-b N"

case "$1" in
    start)
	syslogd -S $FILE $REMOTE $ROTATE_SIZE $ROTATE_N
        ;;
    stop)
	kill `cat $PIDFILE`
        ;;
esac
