#!/bin/sh
#
# This is a minmal rcS file for target startup
#

# Proc & Sys
[ ! -d /proc ] && mkdir /proc
mount -t proc proc /proc
[ ! -d /sys ] && mkdir /sys
mount -t sysfs sysfs /sys

# Mount filesystems in fstab
grep -v noauto /etc/fstab | grep -v '^#' | while read t d rest ; do
    [ "${d#/}" != "$d" ] || continue
    [ -d $d ] || mkdir -p $d
done
mount -a

# Fire startup scripts
. /etc/init.d/rc S

exit 0
